import { app, BrowserWindow, ipcMain } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const CHILD_WINDOW_WEBPACK_ENTRY: string;
declare const CHILD_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow
const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 400,
    width: 500,
    show: false,
    frame: false,
    alwaysOnTop: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false
    },
  });

  // mainWindow.setWindowButtonVisibility(true)

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.on('ready-to-show', () => {
    mainWindow.show()
  })

  // Open the DevTools only in development
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
};

// IPC handlers - fuera de createWindow para que estén disponibles globalmente
ipcMain.on('close-app', () => {
  if (mainWindow) {
    mainWindow.close()
  }
})

ipcMain.on('minimize-app', () => {
  if (mainWindow) {
    mainWindow.minimize()
  }
})

ipcMain.on('maximize-app', () => {
  if (mainWindow) {
    if (mainWindow.isMaximized()) {
      mainWindow.unmaximize()
    } else {
      mainWindow.maximize()
    }
  }
})

let childWindow: BrowserWindow | null = null;

ipcMain.on('open-child-win', (ev, data) => {
  childWindow = new BrowserWindow({
    height: 300,
    width: 400,
    show: false,
    frame: false,
    alwaysOnTop: true,
    webPreferences: {
      preload: CHILD_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  childWindow.loadURL(CHILD_WINDOW_WEBPACK_ENTRY);

  // document.onreadstatechange
  childWindow.on('ready-to-show', () => {
    childWindow?.show()
    mainWindow.hide()
    console.log("data", data);    
  })

  childWindow.on('show', () => {
    childWindow?.webContents.send('tasks-data', data)
  })

  childWindow.on('closed', () => {
    console.log("child win I have closed");
    childWindow = null;
    mainWindow.show()
  })

})

ipcMain.on('minimize-child-win', () => {
  if (childWindow) {
    childWindow.minimize()
  }
})

ipcMain.on('maximize-child-win', () => {
  if (childWindow) {
    if (childWindow.isMaximized()) {
      childWindow.unmaximize()
    } else {
      childWindow.maximize()
    }
  }
})

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.